plugins:
  radiant_member_enabled:
    default: true
    client: true
  radiant_group_values:
    default: "rfp-author:1|rfp-commenter:2500"
    client: true
  radiant_user_cache_minutes:
    default: 720
    client: false
  radiant_dollar_cache_minutes:
    default: 720
    client: false
  radiant_quicknode_arb:
    default: ""
    client: false
  radiant_quicknode_bsc:
    default: ""
    client: false
  radiant_quicknode_eth:
    default: ""
    client: false
  radiant_arbitrum_subgraph_api_key:
    default: ""
    client: false
  radiant_ethereum_subgraph_api_key:
    default: ""
    client: false
