plugins:
  radiant_member_enabled:
    default: true
    client: true
  radiant_group_values:
    default: "rfp-author:1|rfp-commenter:2500"
    client: true
  radiant_user_cache_minutes:
    default: 1440
    client: false
  radiant_dollar_cache_minutes:
    default: 1440
    client: false
